### PR TITLE
Sharding

### PR DESCRIPTION
**Pull request by edison5885**

### CODE REVIEW

**Comment by edison5885** [comment]
done

**Comment by markus456** [comment]
This pretty much completely rewrites the docker-compose setup. Is there a reason for this?

**Comment by Zohan** [comment]
> This pretty much completely rewrites the docker-compose setup. Is there a reason for this?
This was accidentally submitted by one of my students, and was their final project. In the project they convert docker-compose's master-slave setup to shard.
You can safely ignore this PR.

**Comment by markus456** [comment]
OK, thanks for letting us know.

**Pull request closed without merging**
